<template>
  <div id="content">
      <h1>CREATION DE PIZZA</h1>
      
      <div class="container">
         
         <div class="my_card">
              <b-card title="Card title" sub-title="Card subtitle">
                <b-card-text>
                  <p class="lorem">CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA CREATION DE PIZZA </p>
                </b-card-text>

                <b-card-text>A second paragraph of text in the card.</b-card-text>

                <a href="#" class="card-link">Card link</a>
                <b-link href="#" class="card-link">Another link</b-link>
              </b-card>
        </div>
        
      </div>
      
  </div>
</template>

<script>

export default {
  
}
</script>

<style scoped>
    h1 {
        padding-top: 100px;
        margin-top: -72px;
        padding-bottom: 30px;
    }
</style>
